//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Demo.rc
//
#define ID_BLOB_FILL                    2
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DEMOTYPE                    129
#define IDD_TEMP_MATCH                  130
#define IDD_DLGTEMP                     130
#define IDD_DIALOG1                     131
#define IDD_DLGCAL                      132
#define IDD_FEAT_MATCH                  134
#define IDD_DLG_IMHIST                  135
#define IDD_DLG_IMLINTRANS              136
#define IDD_DLG_IMROTATE                137
#define IDD_DLG_IM_TRANSLATE            138
#define IDD_DLG_BLOB_AREA               139
#define IDD_THRESHOLD                   140
#define IDR_MAINFRAME_ORIGIN            144
#define IDC_BUTTON_MAKINGCALFILE        1000
#define IDC_BUTTON_SAVECALFILE          1001
#define IDC_BUTTON_RESTORECALFILE       1002
#define IDC_BUTTON_TRANSFORMIMG         1003
#define IDC_BUTTON_GETGRIDCORNERS       1004
#define IDC_BUTTON_PIX2WORLD            1005
#define IDC_BUTTON_SAVERESULT           1006
#define IDC_BUTTON_CROSSPIXDISTANCE     1007
#define IDC_BUTTON_SHOWRESULT           1008
#define IDC_EDIT1                       1009
#define IDC_EDIT_POSX                   1009
#define IDC_MODELX                      1009
#define IDC_LINTRANS_A                  1009
#define IDC_ROTATE_ANGLE                1009
#define IDC_TRANSLATE_X                 1009
#define IDC_EDIT_LOW                    1009
#define IDC_THRESHOLD                   1009
#define IDC_EDIT2                       1010
#define IDC_EDIT_POSY                   1010
#define IDC_MODELY                      1010
#define IDC_LINTRANS_B                  1010
#define IDC_ROTATE_X                    1010
#define IDC_TRANSLATE_Y                 1010
#define IDC_EDIT_HIGH                   1010
#define IDC_EDIT3                       1011
#define IDC_EDIT_WIDTH                  1011
#define IDC_MODELWIDTH                  1011
#define IDC_ROTATE_Y                    1011
#define IDC_EDIT_FILL                   1011
#define IDC_EDIT4                       1012
#define IDC_EDIT_HEIGHT                 1012
#define IDC_MODELLENGHT                 1012
#define IDC_TEMP_MAKE_MODEL             1013
#define IDC_TEMP_LOAD_MODEL             1014
#define IDC_BUTTON1                     1014
#define IDC_MAKECALFILE                 1014
#define IDC_LOCATEMODEL                 1014
#define IDC_BTN_RESULT                  1014
#define IDC_TEMP_SAVE_MODEL             1015
#define IDC_BUTTON2                     1015
#define IDC_SAVECALFILE                 1015
#define IDC_LOCATEROI                   1015
#define IDC_TEMP_MATCH                  1016
#define IDC_BUTTON3                     1016
#define IDC_RESTORECALFILE              1016
#define IDC_TRAIN                       1016
#define IDC_TEMP_MATCH2                 1017
#define IDC_BUTTON4                     1017
#define IDC_TRANSFORMIMG                1017
#define IDC_TEMP_MATCHALL               1017
#define IDC_MATCHSINGLE                 1017
#define IDC_BUTTON5                     1018
#define IDC_GETCORERS_PIX               1018
#define IDC_TEMP_GETMODEL               1018
#define IDC_MATCHMULTI                  1018
#define IDC_BUTTON6                     1019
#define IDC_TRANSFORMCOORDINATE         1019
#define IDC_EDIT_POX_ROI                1019
#define IDC_LoadModel                   1019
#define IDC_BUTTON7                     1020
#define IDC_CACULATEDISTANCE            1020
#define IDC_EDIT_POSY_ROI               1020
#define IDC_SaveModel                   1020
#define IDC_BUTTON8                     1021
#define IDC_SAVEDISNTANCE               1021
#define IDC_EDIT_WIDTH_ROI              1021
#define IDC_BUTTON9                     1022
#define IDC_PIXDISTANCEIN               1022
#define IDC_EDIT_HEIGHT_ROI             1022
#define IDC_BUTTON10                    1023
#define IDC_WORLDDISTANCEOUT            1023
#define IDC_TEMP_GETIMGROI              1023
#define IDC_TEMP_SETIMGROI              1024
#define IDC_TEMP_SETMODELROI            1025
#define IDC_TEMP_ALLIMG                 1026
#define IDC_TEMP_ALLIMG_ROI             1027
#define IDC_EDIT_ACCEPTANCE             1028
#define IDC_SHOW_MODEL                  1029
#define IDC_SHOW_MATCH                  1030
#define IDC_SAVE_MODELIMG               1031
#define IDC_MATCH_POSX                  1032
#define IDC_MATCH_POSY                  1033
#define IDC_MODELIMAGE                  1033
#define IDC_MATCH_ANGLE                 1034
#define IDC_GRAYFACTOR                  1034
#define IDC_MATCH_SCORE                 1035
#define IDC_WHOLEIMAGE                  1035
#define IDC_MATCH_TIME                  1036
#define IDC_TROIX                       1036
#define IDC_TROIY                       1037
#define IDC_TROIWIDTH                   1038
#define IDC_TROILENGTH                  1039
#define IDC_ACCEPTANCE                  1040
#define IDC_WHOLETARGET                 1041
#define IDC_POSX                        1042
#define IDC_POSY                        1043
#define IDC_TIME                        1044
#define IDC_SCORE                       1045
#define IDC_SCORE1                      1045
#define IDC_SAVEIMG                     1046
#define IDC_STATIC_CHART                1047
#define IDC_ROTATE_DEG                  1048
#define IDC_ROTATE_RAD                  1049
#define IDC_RADIO1                      1049
#define IDC_RADIO2                      1050
#define IDC_COMBO_CLUDE                 1052
#define IDC_COMBO_RANGE                 1054
#define IDC_LIST1                       1055
#define IDC_COMBO_FILL                  1056
#define IDC_MANUAL                      1057
#define IDC_ITERATE                     1058
#define IDC_OSTU                        1059
#define IDC_SMODEL                      1061
#define IDM_OPENFOLDER                  32771
#define ID_TEMP_MATCH                   32772
#define IDM_CALMETHOLD1                 32773
#define IDM_EROSION                     32775
#define IDM_DILATION                    32776
#define IDM_OPENING                     32777
#define IDM_CLOSING                     32778
#define IDM_AVERRAGEFILTER3X3           32779
#define IDM_AVERAGEFILTER5              32780
#define IDM_MEDIANFILTER3               32781
#define ID_IM_LINTRANS                  32782
#define ID_IM_HIST                      32783
#define ID_IM_TRANSLATE                 32784
#define ID_IM_ROTATE                    32785
#define ID_IM_FFT                       32786
#define IDM_MEDIANFILTER5               32787
#define IDM_SOBELFILTERT_THICK          32788
#define IDM_SOBELFILTER_THIN            32789
#define ID_BLOB_AREA                    32790
#define IDM_THRESHOLD                   32791
#define IDM_FEATMATCH                   65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
